    INSERT INTO book (BookID, BookName, TypeID, StatusID, Publish, UnitPrice, UnitRent, DayAmount, Picture, BookDate)
    VALUES
    ('00001', 'Doraemon', '001', '01', 'Kpn', 150, 3, 2, '-', '2554-02-01'),
    ('00002', 'เก็บตะวัน', '002', '03', 'WRP', 250, 5, 3, '-', '2554-03-20'),
    ('00003', 'สิ่งมีชีวิต', '002', '01', 'YPR', 185, 3, 3, '-', '2553-03-25'),
    ('00004', 'คู่สร้างคู่สม', '003', '01', 'DDR', 20, 1, 2, '-', '2552-01-15'),
    ('00005', 'Konan', '001', '02', 'Kpn', 80, 2, 2, '-', '2554-04-08');
    INSERT INTO customer (CustomerID, CustomerName, CustomerSurname, CustomerAddr, CustomerPhone)
    VALUES
    ('0001', 'สมชัย', 'เชียงพงศ์พันธ์ุ', 'ปราจีนบุรี', '037213219'),
    ('0002', 'Jone', 'Smith', 'กรุงเทพ', '027341293');
